build:
  test:
    image: golang:1.8
    commands:
      - make dependencies
      - make test-coverage
  packages:
    image: golang:1.8
    commands:
      - make packages
    when:
      event: tag

compose:
  rabbitmq:
    image: rabbitmq
