language: go

go:
  - 1.8.1
  - tip

go_import_path: gopkg.in/src-d/core-retireval.v0

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

install:
  - make dependencies

script:
  - make test-coverage
  - make ensure-models-generated
